### ISSUE TITLE
Update jQuery version

### ISSUE THREAD

**Issue by pgesek** [benetech/MathEditor#142]
I am getting this alert on GitHub:

jQuery before 3.0.0 is vulnerable to Cross-site Scripting (XSS) attacks when a cross-domain Ajax request is performed...

**CVE-2015-9251** - Moderate severity

We should update jQuery once we have a chance.

**Comment by NSoiffer** [comment]
We use jquery 3.2.1.

Yesterday I updated the "info" package (our help library) because github
warned of a potential security problem in their package specification. It
looks like github got confused about the contents of a new file due to a
comment in one of their examples that some file was from an early version
of jquery. Since we don't use the examples, I simply removed them. I
believe this has resolved the warning as I don't see it anymore.

    Neil

**Comment by pgesek** [comment]
Yep, warning is gone. Closing, thanks.
