### ISSUE TITLE
Connect backend and frontend

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathEditor#360]
If frontend and backend applications will be deployed on the same server, with different ports, communication between them would violate same-origin policy, which is unwanted. Find the best way to hold both applications on one server and communicate between them. In addition, before issues #333 or #334 will be done, it's required to load problem sets from the database, so we could reference them while creating or editing problems solutions. Communication between subpages should work as before connection to the backend. 

For CORS support, see: https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/cors.html#_global_cors_configuration
The list of allowed origins should be configurable.

**Comment by oskarhinc** [comment]
Despite I've said that we should avoid the cross-origin policy, after my research I discovered that allowing cross-origin requests, but only for specified host and port (our frontend app) should not cause any troubles. So I've added configuration to our backend server, and now cross-origin requests are allowed only for the specified host. @pgesek do you think it's a good/secure solution?

**Comment by pgesek** [comment]
@oskarhinc 

Spring has CORS support built in:

https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/cors.html#_global_cors_configuration

We should use the global CORS config. The allowed origins field should be configurable externally, through env properties, so that the server can set the allowed origins for it.
