### ISSUE TITLE
palette fixes/edits

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#78]
- \triangle is incorrect and doesn't match symbol
- "cross out with replacement" should be changed to "cross out and replace"; missing shortcut key (consider using "shift+insert")
- degree symbol shortcut should be \degree (currently has extra "l" at end)
- calc needs shortcut key (consider using "==")
- "Add Step" should have shortcut key (consider using the "enter" or "shift+enter" key on keyboard)

Questions for Neil: 
- "floor" and "ceiling" are missing shortcut keys (any suggestions on what to use?)
- question for Neil: symbols to consider removing from palette (because they're all on the keyboard): parenthesis, brackets, absolute value

**Comment by NSoiffer** [comment]
Addressing the issues one by one:

- _\triangle is incorrect and doesn't match symbol_
  - This is a mathlive bug (it's grabbing the longer command \triangleq). See https://github.com/arnog/mathlive/issues/44.
- _"cross out with replacement" should be changed to "cross out and replace"; missing shortcut key (consider using "shift+insert")._
  - I fixed the name.
  - The keyboard shortcut is a little tricky. The cross out actually has two shortcuts: shift+delete and shift+backspace which mirrors what delete & backspace do (they do the same thing when there is a selection). By extension, some modification of delete and backspace make sense for this rather than using 'insert'. Insert has the other problem that several screen readers use it as their special key.
I ended up using shift+ctrl+backspace/delete.
- _degree symbol shortcut should be \degree (currently has extra "l" at end)_
  - Fixed
- _calc needs shortcut key (consider using "==")_
  - After starting to work on it, I realized that a keyboard shortcut, at least one that uses multiple keys, doesn't make sense. You need a selection and _typing_ `==` means you don't have a selection. It could potentially select everything to the left, but then it works differently than the palette items. We could go with cntrl+=
- _"Add Step" should have shortcut key (consider using the "enter" or "shift+enter" key on keyboard)_
  - I went with 'shift+enter' because 'enter' will get used for multi-line equations.

**Comment by NSoiffer** [comment]
Fixed except for separate issue
